### ISSUE TITLE
Adding citations via a .bib?

### ISSUE THREAD

**Issue by maelle** [ryanpeek/markdown_cv#1]
Nice repo!

I'm wondering whether it'd make sense to add articles via a .bib or DOI with https://github.com/cboettig/knitcitations instead of writing them by hand, not sure how to do this exactly but I was just thinking it might be easier to copy-paste DOI than the whole citations and to have a .bib file that could be used with different bibliography styles? Not sure how to cite citations without having the citations appear anywhere but rather only the list of references at the end.

Soon ORCID will allow to export citations to Bibtex if I understand [this](https://trello.com/c/a6UXNRZu/2583-export-to-bibtex-option-on-the-ui) correctly.

**Comment by ryanpeek** [comment]
Thanks @maelle ...I obviously haven't checked very regularly (unfortunately)! Sorry to just be responding now. I totally agree, I was looking into this a bit more recently. @svmiller's blog post mentions using [RefManageR](https://cran.r-project.org/web/packages/RefManageR/index.html), but I know there a few other bib packages that might work for this sort of thing. I think it does depend on how many you want to include, and if it makes sense. I'll check out the ORCID export, that would be great. 

PS, love your blog! 👍

**Comment by maelle** [comment]
Thanks for looking into this and thanks for the compliment about my blog (which I've neglected a bit in the last weeks :see_no_evil: )!

**Comment by andrewcstewart** [comment]
I use the following pattern (see bottom couple lines in example below) quite often in my reports and was wondering if it would work with this template.  Sure enough it does!  

```
---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Ryan A. Peek
orcid: "orcid.org/0000-0002-9577-6885"
jobtitle: "PhD Candidate, Ecology, UC Davis"
fontawesome: yes
email: rapeek@ucdavis.edu
github: ryanpeek
#phone: "+1 555 5555"
web: ryanpeek.github.io
updated: yes

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue

bibliography: references.bib
nocite: | 
  @article1, @article2, @article3, @article4, @article5
---
```
